version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - add_ssh_keys:
          fingerprints:
            - "ac:75:2a:70:30:0a:c0:a2:3d:f0:7e:02:b1:a8:65:d6"
      - run: |
          if [ $CIRCLE_BRANCH = "master" ]
          then
            yarn release
          fi
