version: 2
jobs:
  deploy-job:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "34:2d:57:85:c5:a4:43:09:c7:c7:f3:1e:2f:e2:7b:64"
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: |
          if [ $CIRCLE_BRANCH = "master" ]
          then
            yarn release
          fi
