version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16.0

jobs:
  build:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - '34:2d:57:85:c5:a4:43:09:c7:c7:f3:1e:2f:e2:7b:64'

      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-hl-design-system-{{ checksum "yarn.lock" }}
            - v1-hl-design-system-

      - run:
          name: Check that yarn.lock is not corrupted
          command: yarn repo-dirty-check

      - run:
          name: Install Dependencies with Yarn
          command: yarn install --ignore-engines

      - save_cache:
          name: Save Yarn Package Cache
          key: v1-hl-design-system-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run:
          name: react-scripts test
          command: yarn test

  release:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      #      - run:
      #          name: auto release
      #          command: |
      #            if [ $CIRCLE_BRANCH = "master" ]
      #            then
      #              yarn release
      #            fi

      - run:
          name: Semantic Release
          command: yarn semantic-release
          no_output_timeout: 5m

workflows:
  version: 2
  hl-design-system-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
